### ISSUE TITLE
update SICF files

### ISSUE THREAD

**Issue by larshp** [hardyp/AbapToTheFuture03#7]
also please upgrade to latest abapGit version and push the SICF files again

related: https://github.com/larshp/abapGit/pull/2453

**Comment by hardyp** [comment]
I am at version 1.84.0 at the moment. What is the latest version? I am currently getting an error message when trying to PULL the latest version of abapGit
![image](https://user-images.githubusercontent.com/7078215/53334553-786e0880-38f9-11e9-863e-8a9b32b64c69.png)

**Comment by larshp** [comment]
the message about texts are okay, if you have pulled the latest it is the latest
