### ISSUE TITLE
excel

### ISSUE THREAD

**Issue by larshp** [hardyp/AbapToTheFuture03#9]
from include Z_MONSTER_MONITOR_IO1,

* Looks like the code requires abap2xlsx to run?
* Object `ztexcel_template` is missing, it looks like its not part of https://github.com/sapmentors/abap2xlsx

```abap
            DATA: ls_template     TYPE ztexcel_template,
                  lo_excel_reader TYPE REF TO zif_excel_reader,
                  lo_worksheet    TYPE REF TO zcl_excel_worksheet.
```

**Comment by hardyp** [comment]
I have added the missing ZTEXCEL_TEMPLATE definition to the repository.
